name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
    getdir:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        outputs:
            matrix: ${{ steps.output_matrix.outputs.matrix }}
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
            - id: output_matrix
              run: |
                  echo "matrix=$(ls | jq -R -s -c '{ "dirs": split("\n")[:-1] }')" > $GITHUB_OUTPUT

    docker_build_push:
        runs-on: ubuntu-latest
        needs: [ getdir ]
        permissions:
            contents: read
            packages: write
        env:
            USER: user
            USER_ID: 1000
            GROUP_ID: 1000
        strategy:
            matrix: ${{ fromJSON(needs.getdir.outputs.matrix) }}
        defaults:
            run:
                working-directory: ${{ matrix.dirs }}
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
            - name: Login ghcr.io
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Docker Compose Build
              run: docker compose build
            - name: Docker Compose Push
              run: docker compose push